export interface WorldCupTeam {
  slug: string;
  name: string;
  flagEmoji: string;
  colors: string; // prompt 用：球队代表色
  jerseyDesc: string; // prompt 用：球衣描述
  stickers: { file: string; caption: string }[]; // 该队主题贴纸（球队页 marquee，每队7张）
  star?: { file: string; name: string }; // 当家球星卡通（仅 AI 高还原度球队）
  promptIdeas: string[];
}

// 8 个热门球队，覆盖 GSC 高需求市场（南美/欧洲/北美/亚洲）
// slug 用作 URL：/world-cup/teams/{slug}
export const WORLD_CUP_TEAMS: WorldCupTeam[] = [
  {
    slug: "brazil",
    name: "Brazil",
    flagEmoji: "🇧🇷",
    colors: "yellow, green and blue",
    jerseyDesc: "yellow and green jersey",
    stickers: [
      { file: "brazil-world-cup-sticker.png", caption: "Football" },
      { file: "brazil-player-sticker.png", caption: "Player" },
      { file: "brazil-mascot-sticker.png", caption: "Toucan" },
      { file: "brazil-fan-sticker.png", caption: "Fan" },
      { file: "brazil-jersey-sticker.png", caption: "Jersey" },
      { file: "brazil-flag-sticker.png", caption: "Flag" },
      { file: "brazil-champion-sticker.png", caption: "Champion" },
    ],
    star: { file: "star-brazil-sticker.png", name: "Neymar" },
    promptIdeas: [
      "a chibi football player in Brazil yellow jersey celebrating a goal",
      "a cute football wearing Brazil flag as a cape",
      "a kawaii toucan with Brazil flag colors",
    ],
  },
  {
    slug: "argentina",
    name: "Argentina",
    flagEmoji: "🇦🇷",
    colors: "sky blue and white",
    jerseyDesc: "blue and white striped jersey",
    stickers: [
      { file: "argentina-world-cup-sticker.png", caption: "Jersey" },
      { file: "argentina-player-sticker.png", caption: "Player" },
      { file: "argentina-mascot-sticker.png", caption: "Jaguar" },
      { file: "argentina-fan-sticker.png", caption: "Fan" },
      { file: "argentina-jersey-sticker.png", caption: "Jersey" },
      { file: "argentina-flag-sticker.png", caption: "Flag" },
      { file: "argentina-champion-sticker.png", caption: "Champion" },
    ],
    star: { file: "star-argentina-sticker.png", name: "Messi" },
    promptIdeas: [
      "a chibi football player in Argentina blue-white striped jersey",
      "a cute football with Argentina sun emblem from flag",
      "a cartoon fan waving Argentina flag",
    ],
  },
  {
    slug: "france",
    name: "France",
    flagEmoji: "🇫🇷",
    colors: "blue, white and red",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "france-world-cup-sticker.png", caption: "Football" },
      { file: "france-player-sticker.png", caption: "Player" },
      { file: "france-mascot-sticker.png", caption: "Rooster" },
      { file: "france-fan-sticker.png", caption: "Fan" },
      { file: "france-jersey-sticker.png", caption: "Jersey" },
      { file: "france-flag-sticker.png", caption: "Flag" },
      { file: "france-champion-sticker.png", caption: "Champion" },
    ],
    star: { file: "star-france-sticker.png", name: "Mbappé" },
    promptIdeas: [
      "a chibi football player in France blue jersey",
      "a cute football wearing France tricolor flag as a cape",
      "a cartoon rooster with France flag colors",
    ],
  },
  {
    slug: "germany",
    name: "Germany",
    flagEmoji: "🇩🇪",
    colors: "black, red and gold",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "germany-world-cup-sticker.png", caption: "Jersey" },
      { file: "germany-player-sticker.png", caption: "Player" },
      { file: "germany-mascot-sticker.png", caption: "Eagle" },
      { file: "germany-fan-sticker.png", caption: "Fan" },
      { file: "germany-jersey-sticker.png", caption: "Jersey" },
      { file: "germany-flag-sticker.png", caption: "Flag" },
      { file: "germany-champion-sticker.png", caption: "Champion" },
    ],
    promptIdeas: [
      "a chibi football player in Germany white jersey",
      "a cute football with Germany black-red-gold colors",
      "a cartoon eagle wearing Germany colors",
    ],
  },
  {
    slug: "england",
    name: "England",
    flagEmoji: "🦁",
    colors: "red and white",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "england-world-cup-sticker.png", caption: "Football" },
      { file: "england-player-sticker.png", caption: "Player" },
      { file: "england-mascot-sticker.png", caption: "Lion" },
      { file: "england-fan-sticker.png", caption: "Fan" },
      { file: "england-jersey-sticker.png", caption: "Jersey" },
      { file: "england-flag-sticker.png", caption: "Flag" },
      { file: "england-champion-sticker.png", caption: "Champion" },
    ],
    star: { file: "star-england-sticker.png", name: "Bellingham" },
    promptIdeas: [
      "a chibi football player in England white jersey",
      "a cute football with England Saint George red cross flag",
      "a cartoon lion wearing England flag colors",
    ],
  },
  {
    slug: "usa",
    name: "USA",
    flagEmoji: "🇺🇸",
    colors: "red, white and blue",
    jerseyDesc: "red and white striped jersey",
    stickers: [
      { file: "usa-world-cup-sticker.png", caption: "Football" },
      { file: "usa-player-sticker.png", caption: "Player" },
      { file: "usa-mascot-sticker.png", caption: "Dog" },
      { file: "usa-fan-sticker.png", caption: "Fan" },
      { file: "usa-jersey-sticker.png", caption: "Jersey" },
      { file: "usa-flag-sticker.png", caption: "Flag" },
      { file: "usa-champion-sticker.png", caption: "Champion" },
    ],
    promptIdeas: [
      "a cartoon football with USA stars and stripes flag",
      "a chibi football player in USA jersey",
      "a cute puppy with USA flag colors",
    ],
  },
  {
    slug: "mexico",
    name: "Mexico",
    flagEmoji: "🇲🇽",
    colors: "green, white and red",
    jerseyDesc: "green jersey",
    stickers: [
      { file: "mexico-world-cup-sticker.png", caption: "Football" },
      { file: "mexico-player-sticker.png", caption: "Player" },
      { file: "mexico-mascot-sticker.png", caption: "Chihuahua" },
      { file: "mexico-fan-sticker.png", caption: "Fan" },
      { file: "mexico-jersey-sticker.png", caption: "Jersey" },
      { file: "mexico-flag-sticker.png", caption: "Flag" },
      { file: "mexico-champion-sticker.png", caption: "Champion" },
    ],
    star: { file: "star-mexico-sticker.png", name: "Chicharito" },
    promptIdeas: [
      "a pixel art football with Mexico flag colors",
      "a chibi football player in Mexico green jersey",
      "a cute soccer ball with Mexico eagle emblem",
    ],
  },
  {
    slug: "japan",
    name: "Japan",
    flagEmoji: "🇯🇵",
    colors: "red and white",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "japan-world-cup-sticker.png", caption: "Samurai" },
      { file: "japan-player-sticker.png", caption: "Player" },
      { file: "japan-mascot-sticker.png", caption: "Crane" },
      { file: "japan-fan-sticker.png", caption: "Fan" },
      { file: "japan-jersey-sticker.png", caption: "Jersey" },
      { file: "japan-flag-sticker.png", caption: "Flag" },
      { file: "japan-champion-sticker.png", caption: "Champion" },
    ],
    promptIdeas: [
      "a kawaii samurai football player with Japan rising sun",
      "a chibi football player in Japan blue jersey",
      "a cute football with Japan red circle flag",
    ],
  },
  {
    slug: "south-africa",
    name: "South Africa",
    flagEmoji: "🇿🇦",
    colors: "gold, green and black",
    jerseyDesc: "gold and green jersey",
    stickers: [
      { file: "south-africa-world-cup-sticker.png", caption: "Football" },
      { file: "south-africa-player-sticker.png", caption: "Player" },
      { file: "south-africa-mascot-sticker.png", caption: "Springbok" },
    ],
    promptIdeas: [
      "a chibi football player in South Africa gold and green jersey celebrating a goal",
      "a cute football wearing South Africa flag colors as a cape",
      "a kawaii springbok antelope with South Africa flag colors",
    ],
  },
  {
    slug: "south-korea",
    name: "South Korea",
    flagEmoji: "🇰🇷",
    colors: "red, blue and black",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "south-korea-player-sticker.png", caption: "Player" },
      { file: "south-korea-mascot-sticker.png", caption: "Tiger" },
    ],
    promptIdeas: [
      "a chibi football player in South Korea red jersey celebrating a goal",
      "a cute football wearing South Korea taegeuk flag colors",
      "a kawaii tiger wearing South Korea flag colors",
    ],
  },
  {
    slug: "czech-republic",
    name: "Czech Republic",
    flagEmoji: "🇨🇿",
    colors: "red, white and blue",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "czech-republic-world-cup-sticker.png", caption: "Football" },
      { file: "czech-republic-mascot-sticker.png", caption: "Lion" },
    ],
    promptIdeas: [
      "a chibi football player in Czech Republic red jersey celebrating a goal",
      "a cute football wearing Czech Republic red-white-blue flag colors",
      "a kawaii lion with Czech Republic crown and flag colors",
    ],
  },
  {
    slug: "canada",
    name: "Canada",
    flagEmoji: "🇨🇦",
    colors: "red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "canada-world-cup-sticker.png", caption: "Football" },
      { file: "canada-player-sticker.png", caption: "Player" },
      { file: "canada-mascot-sticker.png", caption: "Beaver" },
      { file: "canada-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Canada red jersey celebrating a goal",
      "a cute football wearing Canada red maple leaf flag as a cape",
      "a kawaii beaver with Canada flag colors",
    ],
  },
  {
    slug: "bosnia",
    name: "Bosnia and Herzegovina",
    flagEmoji: "🇧🇦",
    colors: "blue, yellow and white",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "bosnia-world-cup-sticker.png", caption: "Football" },
      { file: "bosnia-player-sticker.png", caption: "Player" },
      { file: "bosnia-mascot-sticker.png", caption: "Fleur-de-lis" },
      { file: "bosnia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Bosnia blue jersey celebrating a goal",
      "a cute football wearing Bosnia blue and yellow flag colors",
      "a kawaii golden fleur-de-lis with Bosnia flag colors",
    ],
  },
  {
    slug: "qatar",
    name: "Qatar",
    flagEmoji: "🇶🇦",
    colors: "maroon and white",
    jerseyDesc: "maroon jersey",
    stickers: [
      { file: "qatar-world-cup-sticker.png", caption: "Football" },
      { file: "qatar-player-sticker.png", caption: "Player" },
      { file: "qatar-mascot-sticker.png", caption: "Falcon" },
      { file: "qatar-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Qatar maroon jersey celebrating a goal",
      "a cute football wearing Qatar maroon and white flag colors",
      "a kawaii falcon with Qatar flag colors and desert dunes",
    ],
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    flagEmoji: "🇨🇭",
    colors: "red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "switzerland-world-cup-sticker.png", caption: "Football" },
      { file: "switzerland-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Switzerland red jersey celebrating a goal",
      "a cute football wearing Switzerland white cross on red flag",
      "a kawaii cow with Switzerland flag colors and alpine bell",
    ],
  },
  {
    slug: "morocco",
    name: "Morocco",
    flagEmoji: "🇲🇦",
    colors: "red and green",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "morocco-world-cup-sticker.png", caption: "Football" },
      { file: "morocco-player-sticker.png", caption: "Player" },
      { file: "morocco-mascot-sticker.png", caption: "Atlas Lion" },
      { file: "morocco-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Morocco red jersey celebrating a goal",
      "a cute football wearing Morocco red and green flag colors",
      "a kawaii Atlas lion with Morocco flag colors",
    ],
  },
  {
    slug: "haiti",
    name: "Haiti",
    flagEmoji: "🇭🇹",
    colors: "blue and red",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "haiti-world-cup-sticker.png", caption: "Football" },
      { file: "haiti-player-sticker.png", caption: "Player" },
      { file: "haiti-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Haiti blue jersey celebrating a goal",
      "a cute football wearing Haiti blue and red flag colors",
      "a kawaii palm tree with Haiti flag colors and tropical vibe",
    ],
  },
  {
    slug: "scotland",
    name: "Scotland",
    flagEmoji: "🏴",
    colors: "navy blue and white",
    jerseyDesc: "navy blue jersey",
    stickers: [
      { file: "scotland-world-cup-sticker.png", caption: "Football" },
      { file: "scotland-player-sticker.png", caption: "Player" },
      { file: "scotland-mascot-sticker.png", caption: "Thistle" },
      { file: "scotland-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Scotland navy blue jersey celebrating a goal",
      "a cute football wearing Scotland saltire white cross on blue",
      "a kawaii thistle flower with Scotland flag colors",
    ],
  },
  {
    slug: "paraguay",
    name: "Paraguay",
    flagEmoji: "🇵🇾",
    colors: "red, white and blue",
    jerseyDesc: "red and white striped jersey",
    stickers: [
      { file: "paraguay-world-cup-sticker.png", caption: "Football" },
      { file: "paraguay-player-sticker.png", caption: "Player" },
      { file: "paraguay-mascot-sticker.png", caption: "Jaguar" },
      { file: "paraguay-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Paraguay red and white striped jersey",
      "a cute football wearing Paraguay red-white-blue flag colors",
      "a kawaii jaguar with Paraguay flag colors",
    ],
  },
  {
    slug: "australia",
    name: "Australia",
    flagEmoji: "🇦🇺",
    colors: "gold and green",
    jerseyDesc: "gold jersey",
    stickers: [
      { file: "australia-world-cup-sticker.png", caption: "Football" },
      { file: "australia-player-sticker.png", caption: "Player" },
      { file: "australia-mascot-sticker.png", caption: "Kangaroo" },
      { file: "australia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Australia gold jersey celebrating a goal",
      "a cute football wearing Australia gold and green flag colors",
      "a kawaii kangaroo with Australia flag colors",
    ],
  },
  {
    slug: "turkey",
    name: "Turkey",
    flagEmoji: "🇹🇷",
    colors: "red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "turkey-world-cup-sticker.png", caption: "Football" },
      { file: "turkey-player-sticker.png", caption: "Player" },
      { file: "turkey-mascot-sticker.png", caption: "Crescent" },
    ],
    promptIdeas: [
      "a chibi football player in Turkey red jersey celebrating a goal",
      "a cute football wearing Turkey red flag with white crescent",
      "a kawaii crescent moon and star with Turkey flag colors",
    ],
  },
  {
    slug: "curacao",
    name: "Curaçao",
    flagEmoji: "🇨🇼",
    colors: "blue and yellow",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "curacao-world-cup-sticker.png", caption: "Football" },
      { file: "curacao-player-sticker.png", caption: "Player" },
      { file: "curacao-mascot-sticker.png", caption: "Tropical Fish" },
      { file: "curacao-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Curaçao blue jersey celebrating a goal",
      "a cute football wearing Curaçao blue and yellow flag colors",
      "a kawaii tropical fish with Curaçao Caribbean flag colors",
    ],
  },
  {
    slug: "ivory-coast",
    name: "Ivory Coast",
    flagEmoji: "🇨🇮",
    colors: "orange, white and green",
    jerseyDesc: "orange jersey",
    stickers: [
      { file: "ivory-coast-world-cup-sticker.png", caption: "Football" },
      { file: "ivory-coast-player-sticker.png", caption: "Player" },
      { file: "ivory-coast-mascot-sticker.png", caption: "Elephant" },
      { file: "ivory-coast-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Ivory Coast orange jersey celebrating a goal",
      "a cute football wearing Ivory Coast orange-white-green flag colors",
      "a kawaii elephant with Ivory Coast flag colors",
    ],
  },
  {
    slug: "ecuador",
    name: "Ecuador",
    flagEmoji: "🇪🇨",
    colors: "yellow, blue and red",
    jerseyDesc: "yellow jersey",
    stickers: [
      { file: "ecuador-world-cup-sticker.png", caption: "Football" },
      { file: "ecuador-player-sticker.png", caption: "Player" },
      { file: "ecuador-mascot-sticker.png", caption: "Condor" },
      { file: "ecuador-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Ecuador yellow jersey celebrating a goal",
      "a cute football wearing Ecuador yellow-blue-red flag colors",
      "a kawaii Andean condor with Ecuador flag colors",
    ],
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    flagEmoji: "🇳🇱",
    colors: "orange",
    jerseyDesc: "orange jersey",
    stickers: [
      { file: "netherlands-world-cup-sticker.png", caption: "Football" },
      { file: "netherlands-player-sticker.png", caption: "Player" },
      { file: "netherlands-mascot-sticker.png", caption: "Lion" },
      { file: "netherlands-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Netherlands orange jersey celebrating a goal",
      "a cute football wearing Netherlands orange flag colors",
      "a kawaii tulip with Netherlands orange colors and windmill",
    ],
  },
  {
    slug: "sweden",
    name: "Sweden",
    flagEmoji: "🇸🇪",
    colors: "blue and yellow",
    jerseyDesc: "yellow jersey",
    stickers: [
      { file: "sweden-world-cup-sticker.png", caption: "Football" },
      { file: "sweden-player-sticker.png", caption: "Player" },
      { file: "sweden-mascot-sticker.png", caption: "Viking" },
      { file: "sweden-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Sweden yellow jersey celebrating a goal",
      "a cute football wearing Sweden yellow cross on blue flag",
      "a kawaii viking with Sweden flag colors and helmet",
    ],
  },
  {
    slug: "tunisia",
    name: "Tunisia",
    flagEmoji: "🇹🇳",
    colors: "red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "tunisia-world-cup-sticker.png", caption: "Football" },
      { file: "tunisia-player-sticker.png", caption: "Player" },
      { file: "tunisia-mascot-sticker.png", caption: "Camel" },
      { file: "tunisia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Tunisia red jersey celebrating a goal",
      "a cute football wearing Tunisia red flag with white crescent",
      "a kawaii desert camel with Tunisia flag colors",
    ],
  },
  {
    slug: "belgium",
    name: "Belgium",
    flagEmoji: "🇧🇪",
    colors: "black, yellow and red",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "belgium-world-cup-sticker.png", caption: "Football" },
      { file: "belgium-player-sticker.png", caption: "Player" },
      { file: "belgium-mascot-sticker.png", caption: "Lion" },
      { file: "belgium-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Belgium red jersey celebrating a goal",
      "a cute football wearing Belgium black-yellow-red flag colors",
      "a kawaii waffle with Belgium flag colors",
    ],
  },
  {
    slug: "egypt",
    name: "Egypt",
    flagEmoji: "🇪🇬",
    colors: "red, white and black",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "egypt-world-cup-sticker.png", caption: "Football" },
      { file: "egypt-mascot-sticker.png", caption: "Pyramid" },
      { file: "egypt-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Egypt red jersey celebrating a goal",
      "a cute football wearing Egypt red-white-black flag colors",
      "a kawaii pyramid with Egypt flag colors and golden sand",
    ],
  },
  {
    slug: "iran",
    name: "Iran",
    flagEmoji: "🇮🇷",
    colors: "green, white and red",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "iran-world-cup-sticker.png", caption: "Football" },
      { file: "iran-player-sticker.png", caption: "Player" },
      { file: "iran-mascot-sticker.png", caption: "Persian Cat" },
      { file: "iran-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Iran white jersey celebrating a goal",
      "a cute football wearing Iran green-white-red flag colors",
      "a kawaii Persian cat with Iran flag colors",
    ],
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    flagEmoji: "🇳🇿",
    colors: "black and white",
    jerseyDesc: "black jersey with white fern",
    stickers: [
      { file: "new-zealand-world-cup-sticker.png", caption: "Football" },
      { file: "new-zealand-player-sticker.png", caption: "Player" },
      { file: "new-zealand-mascot-sticker.png", caption: "Kiwi" },
      { file: "new-zealand-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in New Zealand black jersey with white fern",
      "a cute football wearing New Zealand black and silver fern colors",
      "a kawaii kiwi bird with New Zealand flag colors",
    ],
  },
  {
    slug: "spain",
    name: "Spain",
    flagEmoji: "🇪🇸",
    colors: "red and yellow",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "spain-world-cup-sticker.png", caption: "Football" },
      { file: "spain-player-sticker.png", caption: "Player" },
      { file: "spain-mascot-sticker.png", caption: "Bull" },
      { file: "spain-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Spain red jersey celebrating a goal",
      "a cute football wearing Spain red and yellow flag colors",
      "a kawaii fighting bull with Spain flag colors",
    ],
  },
  {
    slug: "uruguay",
    name: "Uruguay",
    flagEmoji: "🇺🇾",
    colors: "blue and white",
    jerseyDesc: "sky blue jersey",
    stickers: [
      { file: "uruguay-world-cup-sticker.png", caption: "Football" },
      { file: "uruguay-player-sticker.png", caption: "Player" },
      { file: "uruguay-mascot-sticker.png", caption: "Capybara" },
      { file: "uruguay-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Uruguay sky blue jersey celebrating a goal",
      "a cute football wearing Uruguay blue and white Sun of May flag",
      "a kawaii gaucho with Uruguay flag colors and horse",
    ],
  },
  {
    slug: "saudi-arabia",
    name: "Saudi Arabia",
    flagEmoji: "🇸🇦",
    colors: "green and white",
    jerseyDesc: "green jersey",
    stickers: [
      { file: "saudi-arabia-world-cup-sticker.png", caption: "Football" },
      { file: "saudi-arabia-player-sticker.png", caption: "Player" },
      { file: "saudi-arabia-mascot-sticker.png", caption: "Falcon" },
      { file: "saudi-arabia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Saudi Arabia green jersey celebrating a goal",
      "a cute football wearing Saudi Arabia green and white flag colors",
      "a kawaii falcon with Saudi Arabia flag colors and desert dunes",
    ],
  },
  {
    slug: "cape-verde",
    name: "Cape Verde",
    flagEmoji: "🇨🇻",
    colors: "blue, white and red",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "cape-verde-world-cup-sticker.png", caption: "Football" },
      { file: "cape-verde-player-sticker.png", caption: "Player" },
      { file: "cape-verde-mascot-sticker.png", caption: "Sea Turtle" },
      { file: "cape-verde-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Cape Verde blue jersey celebrating a goal",
      "a cute football wearing Cape Verde blue-white-red flag colors",
      "a kawaii sea turtle with Cape Verde island flag colors",
    ],
  },
  {
    slug: "senegal",
    name: "Senegal",
    flagEmoji: "🇸🇳",
    colors: "green, yellow and red",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "senegal-world-cup-sticker.png", caption: "Football" },
      { file: "senegal-player-sticker.png", caption: "Player" },
      { file: "senegal-mascot-sticker.png", caption: "Baobab" },
      { file: "senegal-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Senegal white jersey celebrating a goal",
      "a cute football wearing Senegal green-yellow-red flag colors",
      "a kawaii baobab tree with Senegal teranga flag colors",
    ],
  },
  {
    slug: "norway",
    name: "Norway",
    flagEmoji: "🇳🇴",
    colors: "red, white and blue",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "norway-world-cup-sticker.png", caption: "Football" },
      { file: "norway-player-sticker.png", caption: "Player" },
      { file: "norway-mascot-sticker.png", caption: "Troll" },
      { file: "norway-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Norway red jersey celebrating a goal",
      "a cute football wearing Norway red-white-blue flag colors",
      "a kawaii troll with Norway flag colors and fjord mountains",
    ],
  },
  {
    slug: "iraq",
    name: "Iraq",
    flagEmoji: "🇮🇶",
    colors: "red, white and black",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "iraq-world-cup-sticker.png", caption: "Football" },
      { file: "iraq-player-sticker.png", caption: "Player" },
      { file: "iraq-mascot-sticker.png", caption: "Date Palm" },
      { file: "iraq-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Iraq white jersey celebrating a goal",
      "a cute football wearing Iraq red-white-black flag colors",
      "a kawaii date palm tree with Iraq Mesopotamia flag colors",
    ],
  },
  {
    slug: "algeria",
    name: "Algeria",
    flagEmoji: "🇩🇿",
    colors: "green and white",
    jerseyDesc: "green jersey",
    stickers: [
      { file: "algeria-world-cup-sticker.png", caption: "Football" },
      { file: "algeria-player-sticker.png", caption: "Player" },
      { file: "algeria-mascot-sticker.png", caption: "Desert Fox" },
      { file: "algeria-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Algeria green jersey celebrating a goal",
      "a cute football wearing Algeria green and white flag colors",
      "a kawaii desert fox with Algeria Sahara flag colors",
    ],
  },
  {
    slug: "austria",
    name: "Austria",
    flagEmoji: "🇦🇹",
    colors: "red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "austria-world-cup-sticker.png", caption: "Football" },
      { file: "austria-player-sticker.png", caption: "Player" },
      { file: "austria-mascot-sticker.png", caption: "Sachertorte" },
      { file: "austria-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Austria red jersey celebrating a goal",
      "a cute football wearing Austria red and white flag colors",
      "a kawaii slice of Sachertorte with Austria flag colors",
    ],
  },
  {
    slug: "jordan",
    name: "Jordan",
    flagEmoji: "🇯🇴",
    colors: "black, white and green",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "jordan-world-cup-sticker.png", caption: "Football" },
      { file: "jordan-player-sticker.png", caption: "Player" },
      { file: "jordan-mascot-sticker.png", caption: "Petra" },
      { file: "jordan-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Jordan red jersey celebrating a goal",
      "a cute football wearing Jordan black-white-green flag colors",
      "a kawaii Petra treasury with Jordan flag colors and desert",
    ],
  },
  {
    slug: "portugal",
    name: "Portugal",
    flagEmoji: "🇵🇹",
    colors: "red and green",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "portugal-world-cup-sticker.png", caption: "Football" },
      { file: "portugal-player-sticker.png", caption: "Player" },
      { file: "portugal-mascot-sticker.png", caption: "Rooster" },
      { file: "portugal-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Portugal red jersey celebrating a goal",
      "a cute football wearing Portugal red and green flag colors",
      "a kawaii Portuguese rooster with Portugal flag colors",
    ],
  },
  {
    slug: "dr-congo",
    name: "DR Congo",
    flagEmoji: "🇨🇩",
    colors: "sky blue, yellow and red",
    jerseyDesc: "blue jersey",
    stickers: [
      { file: "dr-congo-world-cup-sticker.png", caption: "Football" },
      { file: "dr-congo-player-sticker.png", caption: "Player" },
      { file: "dr-congo-mascot-sticker.png", caption: "Okapi" },
      { file: "dr-congo-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in DR Congo blue jersey celebrating a goal",
      "a cute football wearing DR Congo sky blue-yellow-red flag colors",
      "a kawaii okapi with DR Congo flag colors and jungle leaves",
    ],
  },
  {
    slug: "uzbekistan",
    name: "Uzbekistan",
    flagEmoji: "🇺🇿",
    colors: "blue, white and green",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "uzbekistan-world-cup-sticker.png", caption: "Football" },
      { file: "uzbekistan-player-sticker.png", caption: "Player" },
      { file: "uzbekistan-mascot-sticker.png", caption: "Snow Leopard" },
      { file: "uzbekistan-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Uzbekistan white jersey celebrating a goal",
      "a cute football wearing Uzbekistan blue-white-green flag colors",
      "a kawaii snow leopard with Uzbekistan Silk Road flag colors",
    ],
  },
  {
    slug: "colombia",
    name: "Colombia",
    flagEmoji: "🇨🇴",
    colors: "yellow, blue and red",
    jerseyDesc: "yellow jersey",
    stickers: [
      { file: "colombia-world-cup-sticker.png", caption: "Football" },
      { file: "colombia-player-sticker.png", caption: "Player" },
      { file: "colombia-mascot-sticker.png", caption: "Condor" },
      { file: "colombia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Colombia yellow jersey celebrating a goal",
      "a cute football wearing Colombia yellow-blue-red flag colors",
      "a kawaii toucan with Colombia flag colors and coffee beans",
    ],
  },
  {
    slug: "croatia",
    name: "Croatia",
    flagEmoji: "🇭🇷",
    colors: "red, white and blue",
    jerseyDesc: "red and white checkered jersey",
    stickers: [
      { file: "croatia-world-cup-sticker.png", caption: "Football" },
      { file: "croatia-player-sticker.png", caption: "Player" },
      { file: "croatia-mascot-sticker.png", caption: "Marten" },
      { file: "croatia-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Croatia red and white checkered jersey",
      "a cute football wearing Croatia red-white-blue flag colors",
      "a kawaii Dalmatian dog with Croatia checkered pattern",
    ],
  },
  {
    slug: "ghana",
    name: "Ghana",
    flagEmoji: "🇬🇭",
    colors: "red, yellow and green",
    jerseyDesc: "white jersey",
    stickers: [
      { file: "ghana-player-sticker.png", caption: "Player" },
      { file: "ghana-mascot-sticker.png", caption: "Elephant" },
      { file: "ghana-flag-sticker.png", caption: "Flag" },
    ],
    promptIdeas: [
      "a chibi football player in Ghana white jersey celebrating a goal",
      "a cute football wearing Ghana red-yellow-green flag colors",
      "a kawaii African elephant with Ghana Black Star flag colors",
    ],
  },
  {
    slug: "panama",
    name: "Panama",
    flagEmoji: "🇵🇦",
    colors: "blue, red and white",
    jerseyDesc: "red jersey",
    stickers: [
      { file: "panama-world-cup-sticker.png", caption: "Football" },
      { file: "panama-player-sticker.png", caption: "Player" },
      { file: "panama-mascot-sticker.png", caption: "Toucan" },
    ],
    promptIdeas: [
      "a chibi football player in Panama red jersey celebrating a goal",
      "a cute football wearing Panama blue-red-white flag colors",
      "a kawaii toucan with Panama flag colors and rainforest leaves",
    ],
  },
];

export function getTeamBySlug(slug: string): WorldCupTeam | undefined {
  return WORLD_CUP_TEAMS.find((t) => t.slug === slug);
}

// 各国代表贴纸汇总（球员 + 吉祥物）— 用于 world-cup / es 页轮播，体现"各个国家"
export function getAllTeamShowcaseStickers(): { src: string; alt: string; label: string }[] {
  return WORLD_CUP_TEAMS.flatMap((t) => {
    const player = t.stickers.find((s) => s.caption === "Player");
    const mascot = t.stickers.find((s) => s.file.endsWith("-mascot-sticker.png"));
    return [player, mascot]
      .filter((s): s is { file: string; caption: string } => Boolean(s))
      .map((s) => ({
        src: `/examples/world-cup/${s.file}`,
        alt: `AI generated ${t.name} ${s.caption} World Cup sticker`,
        label: `${t.flagEmoji} ${t.name}`,
      }));
  });
}
