import StickerGenerator from "@/components/StickerGenerator";
import StartCreatingButton from "@/components/StartCreatingButton";
import AdSenseUnit from "@/components/AdSenseUnit";
import { STICKER_STYLES } from "@/lib/sticker-styles";

const FAQ_ITEMS = [
  {
    q: "Can I make WhatsApp stickers without downloading an app?",
    a: "Yes! StickerAI is a web-based tool that works right in your browser. No app download needed — just type your idea, pick a style, and download your custom stickers as PNG files.",
  },
  {
    q: "How do I add AI stickers to WhatsApp?",
    a: "Generate your stickers on StickerAI, download them as PNG images, then import them with your preferred WhatsApp sticker pack tool.",
  },
  {
    q: "Is this AI sticker maker really free?",
    a: "Yes, completely free with no sign up required. We use AI-powered image generation and you can create unlimited stickers without paying anything.",
  },
  {
    q: "What sticker styles are available?",
    a: "We offer 8 styles: Cute Kawaii, Chibi, Pixel Art, Cartoon, Hand-drawn, 3D Rendered, Minimalist, and Retro/Vintage. Each style applies a unique artistic treatment to your sticker idea.",
  },
  {
    q: "Can I use these stickers for Telegram and iMessage too?",
    a: "Yes! Download your stickers as PNG images and they work with Telegram, iMessage, Discord, and any messaging app that supports custom stickers.",
  },
  {
    q: "How do I create a full WhatsApp sticker pack?",
    a: "Generate at least 3 stickers (we recommend 6-12 for a themed pack). Download each one as PNG, then import them together with your preferred WhatsApp sticker pack tool.",
  },
  {
    q: "What makes a good sticker prompt?",
    a: "Be specific and descriptive! Instead of 'cat', try 'a happy orange cat wearing a birthday hat'. The more detail you provide, the better the AI can create your vision. Emotions, accessories, and actions work great.",
  },
  {
    q: "Do I own the stickers I create?",
    a: "The stickers are generated by AI and are free to use for personal purposes like messaging. For commercial use, please check the terms of the AI model used for generation.",
  },
];

function FaqItem({ q, a }: { q: string; a: string }) {
  return (
    <details className="bg-white rounded-2xl p-5 shadow-sm group">
      <summary className="font-semibold text-sm cursor-pointer list-none flex justify-between items-center">
        {q}
        <span className="text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2">
          ▾
        </span>
      </summary>
      <p className="text-sm text-gray-500 mt-3">{a}</p>
    </details>
  );
}

export default function Home() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_ITEMS.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a,
      },
    })),
  };

  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      {/* JSON-LD FAQ Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Hero */}
      <section className="text-center mb-8">
        <p className="text-violet-500 text-sm tracking-widest mb-3 font-semibold">
          AI Sticker Maker
        </p>
        <h1 className="text-3xl md:text-4xl font-bold leading-tight mb-3">
          Free AI WhatsApp Sticker
          <br />
          Maker Online
        </h1>
        <p className="text-gray-500 text-sm mb-1">
          No app download. No sign up. Just type and create.
        </p>
        <p className="text-violet-600 font-semibold text-sm">
          Works with WhatsApp, Telegram, iMessage &amp; Discord
        </p>
      </section>

      {/* Interactive Tool */}
      <StickerGenerator />

      {/* How To Section */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          How to Make WhatsApp Stickers Online Without App
        </h2>
        <p className="text-gray-400 text-center text-sm mb-8">
          Create custom stickers in 3 simple steps
        </p>
        <div className="grid gap-4">
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              1
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Type your sticker idea
              </h3>
              <p className="text-sm text-gray-500">
                Describe what you want — &ldquo;a happy cat wearing
                sunglasses&rdquo; or &ldquo;cute coffee cup with heart
                eyes&rdquo;. The more specific, the better!
              </p>
            </div>
          </div>
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              2
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Pick a style &amp; generate
              </h3>
              <p className="text-sm text-gray-500">
                Choose from 8 styles (Kawaii, Chibi, Pixel Art, etc.) and
                click Generate. AI creates 4 unique sticker variations.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              3
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Download &amp; add to WhatsApp
              </h3>
              <p className="text-sm text-gray-500">
                Download as PNG, then add your custom stickers with your
                preferred sticker pack tool. It&apos;s that easy!
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Style Showcase */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          AI Sticker Generator with Multiple Styles
        </h2>
        <p className="text-gray-400 text-center text-sm mb-8">
          From cute kawaii to retro pixel art — find your perfect style
        </p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {STICKER_STYLES.map((style) => (
            <div
              key={style.id}
              className="bg-white rounded-xl p-4 shadow-sm text-center"
            >
              <span className="text-3xl block mb-2">{style.emoji}</span>
              <p className="font-semibold text-sm">{style.name}</p>
              <p className="text-xs text-gray-400">{style.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Export Guide */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          Export AI Stickers for WhatsApp and Telegram
        </h2>
        <p className="text-gray-400 text-center text-sm mb-6">
          Works everywhere you chat
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">💬</div>
            <h3 className="font-semibold text-sm mb-1">WhatsApp</h3>
            <p className="text-xs text-gray-500">
              Download as PNG and import with a sticker pack tool.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">✈️</div>
            <h3 className="font-semibold text-sm mb-1">Telegram</h3>
            <p className="text-xs text-gray-500">
              Download as PNG. Use @Stickers bot to create a sticker pack.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">🍎</div>
            <h3 className="font-semibold text-sm mb-1">iMessage</h3>
            <p className="text-xs text-gray-500">
              Download as PNG. Use Sticker Maker Studio app to import.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">🎮</div>
            <h3 className="font-semibold text-sm mb-1">Discord</h3>
            <p className="text-xs text-gray-500">
              Upload PNG stickers to your server. 320x320 recommended.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-8">
          Frequently Asked Questions
        </h2>
        <div className="space-y-3">
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.q} q={item.q} a={item.a} />
          ))}
        </div>
      </section>

      {/* Ad Unit - After FAQ */}
      <AdSenseUnit slot={process.env.NEXT_PUBLIC_AD_SLOT_CONTENT ?? ""} />

      {/* CTA */}
      <section className="py-12 text-center">
        <h2 className="text-xl font-bold mb-3">
          Ready to create your stickers?
        </h2>
        <p className="text-sm text-gray-500 mb-6">
          Free, no sign up, no app download
        </p>
        <StartCreatingButton />
      </section>

      {/* Footer */}
      <footer className="text-center py-10 text-xs text-gray-300 border-t border-gray-100 mt-8">
        <p className="text-sm font-semibold text-gray-400 mb-1">StickerAI</p>
        <p>Free AI Sticker Maker for WhatsApp, Telegram &amp; More</p>
      </footer>
    </main>
  );
}
