import StickerGenerator from "@/components/StickerGenerator";
import Link from "next/link";
import StartCreatingButton from "@/components/StartCreatingButton";
import AdSenseUnit from "@/components/AdSenseUnit";
import { STICKER_STYLES } from "@/lib/sticker-styles";

const FAQ_ITEMS = [
  {
    q: "Can I make WhatsApp stickers without downloading an app?",
    a: "Yes! StickerAI at stickersit.com is a web-based tool that works right in your browser — no app download needed. Simply visit stickersit.com, type your sticker idea in the text box, pick one of 8 artistic styles like Kawaii or Pixel Art, and click Generate. Your custom stickers are created in seconds and can be downloaded as PNG files directly to your device. Works on any phone, tablet, or computer.",
  },
  {
    q: "How do I add AI stickers to WhatsApp?",
    a: "Generate your stickers on StickerAI (stickersit.com), then download them as PNG images. Open WhatsApp, go to any chat, tap the sticker icon, and use your sticker pack tool to import the downloaded PNG files. Each sticker should be 512x512 pixels for the best quality. You can also create themed packs of 3-12 stickers and import them all at once.",
  },
  {
    q: "Is this AI sticker maker really free?",
    a: "Yes, StickerAI at stickersit.com is completely free with no sign-up, no email required, and no credit card needed. Unlike many sticker maker apps that charge for premium styles or add watermarks, StickerAI generates unlimited stickers at no cost. You can use all 8 styles (Cute Kawaii, Chibi, Pixel Art, Cartoon, Hand-drawn, 3D Rendered, Minimalist, Retro/Vintage) without any usage limits or hidden fees.",
  },
  {
    q: "What sticker styles are available?",
    a: "StickerAI offers 8 distinct artistic styles: Cute Kawaii (pastel, adorable, soft), Chibi (big head, cute body), Pixel Art (16-bit retro gaming), Cartoon (bold, colorful, fun), Hand-drawn (sketch, doodle style), 3D Rendered (Pixar-like quality), Minimalist (clean, modern, simple), and Retro/Vintage (nostalgic vibes). Each style applies a unique artistic treatment to your sticker idea, so the same prompt can produce very different results across styles.",
  },
  {
    q: "Can I use these stickers for Telegram and iMessage too?",
    a: "Yes! Stickers downloaded from stickersit.com work with all major messaging platforms. For Telegram, use the @Stickers bot to create a sticker pack from your PNG files. For iMessage, import them using Sticker Maker Studio. For Discord, upload PNG stickers to your server (320x320 recommended). The PNG format is universally supported across all messaging apps that allow custom stickers.",
  },
  {
    q: "How do I create a full WhatsApp sticker pack?",
    a: "Generate at least 3 stickers on stickersit.com (we recommend 6-12 for a themed pack). Keep your prompts consistent — for example, use the same style and similar subjects like 'a happy cat cheering', 'a happy cat with a trophy', and 'a happy cat wearing a party hat'. Download each one as PNG, then import them all together using your preferred WhatsApp sticker pack tool. Consistent styling makes your pack look professional.",
  },
  {
    q: "What makes a good sticker prompt?",
    a: "Be specific and descriptive! Instead of 'cat', try 'a happy orange cat wearing a birthday hat with confetti'. The more detail you provide, the better StickerAI can create your vision. Great prompts include: emotions ('excited', 'sleepy'), accessories ('sunglasses', 'crown'), actions ('dancing', 'hugging'), and settings ('in a coffee shop', 'on a beach'). Combine these elements for unique results that match exactly what you imagine.",
  },
  {
    q: "Do I own the stickers I create?",
    a: "The stickers generated by StickerAI at stickersit.com are created by AI and are free to use for personal purposes like messaging friends on WhatsApp, Telegram, iMessage, and Discord. For commercial use (selling, branding, merchandise), please check the terms of the AI model used for generation, as ownership of AI-generated content varies by jurisdiction. Personal, non-commercial use is always fine.",
  },
];

function FaqItem({ q, a }: { q: string; a: string }) {
  return (
    <details className="bg-white rounded-2xl p-5 shadow-sm group">
      <summary className="font-semibold text-sm cursor-pointer list-none flex justify-between items-center">
        {q}
        <span className="text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2">
          ▾
        </span>
      </summary>
      <p className="text-sm text-gray-500 mt-3">{a}</p>
    </details>
  );
}

export default function Home() {
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "https://stickersit.com/#organization",
    name: "StickerAI",
    url: "https://stickersit.com",
    logo: "https://stickersit.com/thumbnail.png",
    description:
      "Free AI-powered sticker maker for WhatsApp, Telegram, iMessage, and Discord.",
    sameAs: ["https://x.com/YangDada3983"],
  };

  const websiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "https://stickersit.com/#website",
    url: "https://stickersit.com",
    name: "StickerAI",
    description: "Free AI WhatsApp Sticker Maker Online",
    publisher: { "@id": "https://stickersit.com/#organization" },
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_ITEMS.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a,
      },
    })),
  };

  const webAppSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "@id": "https://stickersit.com/#webapplication",
    name: "StickerAI",
    url: "https://stickersit.com",
    description:
      "Free AI-powered sticker maker for WhatsApp, Telegram, and iMessage. Create custom stickers online without downloading an app.",
    applicationCategory: "MultimediaApplication",
    operatingSystem: "Any",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    browserRequirements: "Requires JavaScript. Requires HTML5.",
    author: { "@id": "https://stickersit.com/#organization" },
    screenshot: "https://stickersit.com/thumbnail.png",
    featureList:
      "AI-powered sticker generation, 8 artistic styles (Kawaii, Chibi, Pixel Art, Cartoon, Hand-drawn, 3D Rendered, Minimalist, Retro), WhatsApp/Telegram/iMessage/Discord export, no sign-up required, unlimited free usage",
  };

  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to Make WhatsApp Stickers Online Without App",
    description:
      "Create custom AI stickers for WhatsApp without downloading any app. Free and no sign-up required.",
    step: [
      {
        "@type": "HowToStep",
        position: 1,
        name: "Type your sticker idea",
        text: "Describe what you want — 'a happy cat wearing sunglasses' or 'cute coffee cup with heart eyes'. The more specific, the better!",
      },
      {
        "@type": "HowToStep",
        position: 2,
        name: "Pick a style & generate",
        text: "Choose from 8 styles (Kawaii, Chibi, Pixel Art, etc.) and click Generate. AI creates 4 unique sticker variations.",
      },
      {
        "@type": "HowToStep",
        position: 3,
        name: "Download & add to WhatsApp",
        text: "Download as PNG, then add your custom stickers with your preferred sticker pack tool. It's that easy!",
      },
    ],
  };

  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      {/* JSON-LD Schemas */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(organizationSchema),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
      />

      {/* Hero */}
      <section className="text-center mb-8">
        <p className="text-violet-500 text-sm tracking-widest mb-3 font-semibold">
          AI Sticker Maker
        </p>
        <h1 className="text-3xl md:text-4xl font-bold leading-tight mb-3">
          Free AI WhatsApp Sticker
          <br />
          Maker Online
        </h1>
        <p className="text-gray-500 text-sm mb-1">
          No app download. No sign up. Just type and create.
        </p>
        <p className="text-violet-600 font-semibold text-sm">
          Works with WhatsApp, Telegram, iMessage &amp; Discord
        </p>
      </section>

      {/* Interactive Tool */}
      <StickerGenerator />

      {/* World Cup 2026 Banner */}
      <Link href="/world-cup" className="block mb-6">
        <div className="bg-gradient-to-r from-green-500 to-emerald-600 rounded-2xl p-5 shadow-sm hover:shadow-md transition-shadow text-white text-center">
          <p className="text-xs tracking-widest mb-1 font-semibold uppercase opacity-80">
            ⚽ Limited Time
          </p>
          <p className="text-lg font-bold mb-1">
            World Cup 2026 Sticker Maker
          </p>
          <p className="text-sm opacity-90">
            Create custom FIFA World Cup stickers for free →
          </p>
        </div>
      </Link>

      {/* How To Section */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          How to Make WhatsApp Stickers Online Without App
        </h2>
        <p className="text-gray-400 text-center text-sm mb-8">
          Create custom stickers in 3 simple steps
        </p>
        <div className="grid gap-4">
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              1
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Type your sticker idea
              </h3>
              <p className="text-sm text-gray-500">
                Describe what you want — &ldquo;a happy cat wearing
                sunglasses&rdquo; or &ldquo;cute coffee cup with heart
                eyes&rdquo;. The more specific, the better!
              </p>
            </div>
          </div>
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              2
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Pick a style &amp; generate
              </h3>
              <p className="text-sm text-gray-500">
                Choose from 8 styles (Kawaii, Chibi, Pixel Art, etc.) and
                click Generate. AI creates 4 unique sticker variations.
              </p>
            </div>
          </div>
          <div className="bg-white rounded-2xl p-6 shadow-sm flex gap-4 items-start">
            <span className="bg-violet-100 text-violet-600 font-bold text-lg w-10 h-10 rounded-full flex items-center justify-center shrink-0">
              3
            </span>
            <div>
              <h3 className="font-semibold text-sm mb-1">
                Download &amp; add to WhatsApp
              </h3>
              <p className="text-sm text-gray-500">
                Download as PNG, then add your custom stickers with your
                preferred sticker pack tool. It&apos;s that easy!
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Style Showcase */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          AI Sticker Generator with Multiple Styles
        </h2>
        <p className="text-gray-400 text-center text-sm mb-8">
          From cute kawaii to retro pixel art — find your perfect style
        </p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {STICKER_STYLES.map((style) => (
            <div
              key={style.id}
              className="bg-white rounded-xl p-4 shadow-sm text-center"
            >
              <span className="text-3xl block mb-2">{style.emoji}</span>
              <p className="font-semibold text-sm">{style.name}</p>
              <p className="text-xs text-gray-400">{style.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Export Guide */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-3">
          Export AI Stickers for WhatsApp and Telegram
        </h2>
        <p className="text-gray-400 text-center text-sm mb-6">
          Works everywhere you chat
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">💬</div>
            <h3 className="font-semibold text-sm mb-1">WhatsApp</h3>
            <p className="text-xs text-gray-500">
              Download as PNG and import with a sticker pack tool.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">✈️</div>
            <h3 className="font-semibold text-sm mb-1">Telegram</h3>
            <p className="text-xs text-gray-500">
              Download as PNG. Use @Stickers bot to create a sticker pack.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">🍎</div>
            <h3 className="font-semibold text-sm mb-1">iMessage</h3>
            <p className="text-xs text-gray-500">
              Download as PNG. Use Sticker Maker Studio app to import.
            </p>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm text-center">
            <div className="text-3xl mb-2">🎮</div>
            <h3 className="font-semibold text-sm mb-1">Discord</h3>
            <p className="text-xs text-gray-500">
              Upload PNG stickers to your server. 320x320 recommended.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-12">
        <h2 className="text-2xl font-bold text-center mb-8">
          Frequently Asked Questions
        </h2>
        <div className="space-y-3">
          {FAQ_ITEMS.map((item) => (
            <FaqItem key={item.q} q={item.q} a={item.a} />
          ))}
        </div>
      </section>

      {/* Ad Unit - After FAQ */}
      <AdSenseUnit slot={process.env.NEXT_PUBLIC_AD_SLOT_CONTENT ?? ""} />

      {/* CTA */}
      <section className="py-12 text-center">
        <h2 className="text-xl font-bold mb-3">
          Ready to create your stickers?
        </h2>
        <p className="text-sm text-gray-500 mb-6">
          Free, no sign up, no app download
        </p>
        <StartCreatingButton />
      </section>

      {/* Footer */}
      <footer className="text-center py-10 text-xs text-gray-300 border-t border-gray-100 mt-8">
        <p className="text-sm font-semibold text-gray-400 mb-1">StickerAI</p>
        <p className="mb-2">Free AI Sticker Maker for WhatsApp, Telegram &amp; More</p>
        <div className="flex justify-center gap-4 mt-2">
          <a
            href="https://x.com/YangDada3983"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 hover:text-violet-500 transition-colors"
          >
            𝕏 @YangDada3983
          </a>
        </div>
      </footer>
    </main>
  );
}
