import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | StickerAI",
  description:
    "Terms of service for StickerAI — free AI sticker maker for WhatsApp, Telegram, iMessage, and Discord.",
  alternates: { canonical: "https://stickersit.com/terms" },
};

export default function TermsPage() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">
        Last updated: June 3, 2026
      </p>

      <div className="space-y-8 text-sm text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold mb-3">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using StickerAI (stickersit.com), you agree to be
            bound by these Terms of Service. If you do not agree with any part
            of these terms, you may not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">
            2. Description of Service
          </h2>
          <p>
            StickerAI is a free, web-based AI sticker maker that generates
            custom sticker images from text prompts. The service uses AI-powered
            image generation to create stickers that can be downloaded and used
            in messaging apps including WhatsApp, Telegram, iMessage, and
            Discord. No account registration is required.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">3. Usage Rights</h2>
          <p>
            Stickers generated by StickerAI are created using AI image
            generation technology. You may use the generated stickers for
            personal, non-commercial purposes such as sharing in personal
            messaging conversations. Commercial use of generated stickers
            (including selling, merchandising, or branding) is subject to the
            terms of the underlying AI model and applicable intellectual property
            laws.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">
            4. User Conduct
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside mt-2 space-y-1">
            <li>
              Generate stickers that are illegal, harmful, threatening, abusive,
              or otherwise objectionable
            </li>
            <li>
              Use the service to generate content that infringes on
              third-party intellectual property rights
            </li>
            <li>
              Attempt to overwhelm or disrupt the service with excessive
              requests
            </li>
            <li>
              Use automated tools to access the service without authorization
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">
            5. Disclaimer of Warranties
          </h2>
          <p>
            StickerAI is provided &ldquo;as is&rdquo; without warranties of any
            kind. We do not guarantee that the service will be uninterrupted,
            error-free, or that generated stickers will meet your specific
            requirements. AI-generated content may vary in quality and is not
            guaranteed to produce any particular result.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">
            6. Limitation of Liability
          </h2>
          <p>
            In no event shall StickerAI be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of
            the service. This includes, but is not limited to, damages for loss
            of data, goodwill, or other intangible losses.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">7. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued
            use of the service after changes constitutes acceptance of the
            updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">8. Contact</h2>
          <p>
            For questions about these Terms of Service, please reach out through
            our website at stickersit.com.
          </p>
        </section>
      </div>

      <footer className="text-center py-10 text-xs text-gray-300 border-t border-gray-100 mt-8">
        <p className="text-sm font-semibold text-gray-400 mb-1">StickerAI</p>
        <p className="mt-2">
          <Link href="/" className="text-violet-400 hover:text-violet-600">
            &larr; Back to StickerAI Home
          </Link>
        </p>
      </footer>
    </main>
  );
}
